### ISSUE TITLE
Style changes for blog

### ISSUE THREAD

**Issue by simplesquare1** [repositive/liz#1]
- [x] all posts page:change the font and spacing for metadata (see mockup attached)
- [x] post page: Main heading in the middle
- [x] change share icons (same as we used on email template - green)
- [x] align the share and comment section to the left
- [x] view post by a specific autor
- [x] view post by a specific  tag
  ![blog page](https://cloud.githubusercontent.com/assets/13767979/11840248/324c5ad2-a3ec-11e5-9add-de5829b3091c.png)

**Comment by danielgynn** [comment]
All done :+1:
